services:
  - type: web
    name: youtube-mp3-api
    runtime: python
    packages:
      - ffmpeg
    buildCommand: |
      pip install -r requirements.txt &&
      pip install --upgrade yt-dlp
    startCommand: gunicorn app:app --workers 2 --timeout 180 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://TU-FRONTEND.vercel.app
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: '5432'
      - key: DB_NAME
        sync: false
    plan: free
    healthCheckPath: /
